//TODO buat sistem kaya setiap card ada EXP sama Level per Individual User
//TODO BUAT BREADCRUMB

//TODO DI ADD PAGE BISA AJA ADD KAYA ARRAY OF BOOLEAN DIMAANA JIKA USER HABIT CHECKLIST BAKAL CENTANG ITU