//TODO MIGRATE POST REGISTER SAMA LOGIN KE REDUX = tomorrow
//TODO BUAT BREADCRUMB = on-hold
//TODO DI ADD PAGE BISA AJA ADD KAYA ARRAY OF BOOLEAN DIMAANA JIKA USER HABIT CHECKLIST BAKAL CENTANG ITU = not yet worked on

